// HONY-style story learning types

export interface VocabWord {
  word: string;
  context: string;        // original sentence from the story
  definition: string;     // Chinese explanation
  exampleSentence: string;
}

export interface SentencePattern {
  pattern: string;        // the pattern/idiom (e.g., "I never thought I'd...")
  fromStory: string;      // original sentence from the story
  explanation: string;    // Chinese grammar/usage explanation
  practicePrompts: string[]; // prompts for user to make sentences
}

export interface QuizQuestion {
  type: 'comprehension' | 'vocabulary' | 'fill-blank';
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;    // why this is the correct answer (Chinese)
}

export interface Story {
  id: string;
  title: string;
  content: string;        // full story text
  source: string;         // "Generated by AI" / "From HONY archive"
  imageUrl?: string;
  audioUrl?: string;
  vocabulary: VocabWord[];
  patterns: SentencePattern[];
  keywords: string[];     // for retelling
  quiz: QuizQuestion[];
  createdAt: number;
}

export interface StoryProgress {
  storyId: string;
  completedSteps: boolean[];  // 5 booleans
  vocabResults?: { word: string; userSentence: string; feedback: string }[];
  retellRecordingKey?: string;
  retellFeedback?: string;
  quizScore?: number;         // 0-100
  completedAt?: number;
}
